# Generated by Django 6.0.1 on 2026-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_course_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='enrolled_on',
            field=models.DateField(blank=True),
        ),
    ]
