# Generated by Django 6.0.1 on 2026-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentcourseenrollment_enrolled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='enrolled_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
