# Generated by Django 6.0.1 on 2026-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
