# Generated by Django 6.0.1 on 2026-02-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyprofile_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='faculty_role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('hod', 'Hod'), ('admissions_officer', 'Admissions_officer'), ('finance_officer', 'Finance_officer')], default='instructor', max_length=100),
        ),
    ]
