# Generated by Django 6.0.1 on 2026-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_subject_course_course_subjects'),
        ('faculty', '0003_facultyprofile_faculty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='courses.subject'),
        ),
    ]
