# Generated by Django 6.0.1 on 2026-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseattendance_subjectattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
